


export const DISPLAY_LOADING_TRUE = "DISPLAY_LOADING_TRUE";
export const DISPLAY_LOADING_FALSE = "DISPLAY_LOADING_FALSE";



export const GETAPIMOVIETHEATER = "GETAPIMOVIETHEATER";
export const getAPISYSTEMThEATERCLUSTERS = "getAPISYSTEMThEATERCLUSTERS";
export const GET_API_SYSTEM_MOVIE_SHOW = "GETAPISYSTEMMOVIESHOW";
export const GETAPIDETAILMOVIE = "GETAPIDETAILMOVIE";
export const GET_DETAIL_MOVIE_TO_THEATER = "GETDETAILMOVIETOTHEATER";
export const GETPICKBYDAYMOVIE = "GETPICKBYDAYMOVIE"; 
export const FETCH_LIST_DETAIL_THEATER = "FETCH_LIST_DETAIL_THEATER";
export const FETCH_ALL_LIST_SYSTEM_THEATER = "FETCH_ALL_LIST_SYSTEM_THEATER";
/// user 

export const GETDATAUSERLOGIN ="GETDATAUSERLOGIN"; 
export const GET_DATA_REGISTER ="GET_DATA_REGISTER"; 
export const FETCH_DETAIL_USER = "FETCH_DETAIL_USER"; 

//booking 

export const CreateShowtime = "CREATE_SHOW_TIME";

export const CHANGE_STYLE_STEP= "CHANGE_STYLE_STEP";
export const GET_COUNT_CHAIR = "GET_COUNT_CHAIR";
export const GET_COUNT_COMBO = "GET_COUNT_COMBO";

export const GET_DETAIL_CHAIR ="GET_DETAIL_CHAIR";


//admin 
// ----search 
export const CHANGE_STATUS_INDEX = "CHANGE_STATUS_INDEX";

export const CHANGE_STATUS_USERS = "CHANGE_STATUS_USERS";
export const CHANGE_STATUS_MOVIES = "CHANGE_STATUS_MOVIES";

export const POST_VALUE_SEARCH ="POST_VALUE_SEARCH";
export const GET_LIST_USERS = "GET_LIST_USERS";


export const GET_LIST_MOVIES = "GET_LIST_MOVIES";